#! /usr/bin/env bash

set -e

FUNC_DIR="/root/workspace/aws-bootcamp-cruddur-2023/ddb/function"
TEMPLATE_PATH="/root/workspace/aws-bootcamp-cruddur-2023/ddb/template.yaml"
CONFIG_PATH="/root/workspace/aws-bootcamp-cruddur-2023/ddb/config.toml"

sam validate -t $TEMPLATE_PATH

echo "== build"
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html
# --use-container
# use container is for building the lambda in a container
# its still using the runtimes and its not a custom runtime
sam build \
--use-container \
--config-file $CONFIG_PATH \
--template-file $TEMPLATE_PATH \
--base-dir $FUNC_DIR
# --parameter-overrides