#! /usr/bin/bash
set -e

PACKAGED_TEMPLATE_PATH="/root/workspace/aws-bootcamp-cruddur-2023/.aws-sam/build/packaged.yaml"
CONFIG_PATH="/root/workspace/aws-bootcamp-cruddur-2023/ddb/config.toml"

echo "== deploy"

sam deploy \
    --template-file $PACKAGED_TEMPLATE_PATH \
    --config-file $CONFIG_PATH \
    --stack-name "CrdDdb" \
    --tags group="cruddur-ddb" \
    --no-execute-changeset \
    --capabilities "CAPABILITY_NAMED_IAM"
